document.write('<ul class="navlist">');
document.write('<li> <a href="CSS-01.html">Content tags</a></li>');
document.write('<li> <a href="CSS-02.html">Table divisions</a></li>');
document.write('<li> <a href="CSS-03.html">Tags with Styles</a></li>');
document.write('<li> <a href="CSS-04.html">Link Tag Styles</a></li>');
document.write('<li> <a href="CSS-05.html">Content Divisions</a></li>');
document.write('<li> <a href="CSS-06.html">Layout</a></li>');
document.write('<li> <a href="CSS-07.html">Subheading Menu</a></li>');
document.write('<li> <a href="CSS-08.html">Styles a CSS File</a></li>');
document.write('<li> <a href="CSS-09.html">Add footer</a></li>');
document.write('</ul>');
