document.write('<div class="navtitle">JavaScript Samples</div>');
document.write('<ul class="navlist">');
document.write('<li><a id="displayJs01" href="">Drag and drop</a></li>');
document.write('<li><a id="displayJs02" href="">Timer events</a></li>');
document.write('<li><a id="displayJs03" href="">Simple moving image animation</a></li>');
document.write('<li><hr></li>');
document.write('<li><a id="displayJs04" href="">Fish Game</a></li>');
document.write('<li><a id="displayJs05" href="">Fish Game with a counter</a></li>');
document.write('<li><a id="displayJs06" href="">Fish Game with a counter and an explosion graphic</a></li>');
document.write('</ul>');
