document.write('<ul class="navlist">');
document.write('<li> <a href=Javascript:goHome();>Initial State</a></li>');
document.write('<li> <a href=Javascript:dragobject.toggleTileImgGeo();>Satellite View</a></li>');
document.write('<li> <a href=Javascript:dragobject.toggleTileImgPolitical();>Political Map</a></li>');
document.write('<li> <a href=Javascript:goAustralia();>Australia Map</a></li>');
document.write('<li> <a href=Javascript:goCanada();>Canada Satellite View</a></li>');
document.write('<li> <a href=Javascript:goEurope();>Europe</a></li>');
document.write('<li> <a href=Javascript:goIndia();>India</a></li>');
document.write('<li> <a href=Javascript:goUSA();>USA</a></li>');
document.write('</ul>');
